# Site settings
title: dreilopz.com
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  dreilopz's website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dreilopz.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll
permalink: "/blog/:year/:month/:day/:title"

# Build settings
markdown: kramdown
